library(shiny)
library(tidyverse)
library(maps)
library(readr)
library(RColorBrewer)
library(tidyverse)
library(maps)
library(readr)
library(RColorBrewer)
library(sf)
library(Factoshiny)
library(ggrepel)
library(readxl)
library(corrplot)
library(DT)
library(ggridges)
library(leaflet)
library(plotly)
library(viridis)
library(shinythemes)
library(scales)
library(cowplot)
library(stringr)


source("ui.R")
source("server.R")

# Run the application 
shinyApp(ui = ui, server = server)
# runApp()
