library(shiny)
library(tidyverse)
library(maps)
library(readr)
library(RColorBrewer)
library(tidyverse)
library(maps)
library(readr)
library(RColorBrewer)
library(sf)
library(Factoshiny)
library(ggrepel)
library(readxl)
library(corrplot)
library(DT)
library(ggridges)
library(leaflet)

source("ui.R")
source("server.R")

# Run the application 
shinyApp(ui = ui, server = server)
